databases:
  - name: archivedb
    plan: free
    databaseName: archive
    user: archive

services:
  - type: web
    plan: free
    name: archive
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn app.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: archivedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4